import type { PosOrder } from "../pos.types";

const now = Date.now();

export const posSeedOrders: PosOrder[] = [
  {
    id: "#ORD-WEB-1001",
    createdAt: now - 10 * 60 * 1000,
    source: "WEB",
    status: "PENDING",
    fulfillment: "QUEUED",
    customerName: "Nadia Putri",
    tableLabel: "Takeaway",
    serviceMode: "TAKEAWAY",
    items: [
      {
        id: "web-item-1",
        productId: "kopi-susu",
        name: "Kopi Susu",
        qty: 2,
        unitPrice: 22000,
      },
    ],
    payments: [],
    subtotal: 44000,
    discountAmount: 0,
    taxAmount: 4840,
    grandTotal: 48840,
  },
  {
    id: "#ORD-WEB-1002",
    createdAt: now - 40 * 60 * 1000,
    source: "WEB",
    status: "PENDING",
    fulfillment: "QUEUED",
    customerName: "Raka",
    tableLabel: "Takeaway",
    serviceMode: "TAKEAWAY",
    items: [
      {
        id: "web-item-2",
        productId: "nasi-goreng",
        name: "Nasi Goreng",
        qty: 1,
        unitPrice: 32000,
      },
    ],
    payments: [],
    subtotal: 32000,
    discountAmount: 0,
    taxAmount: 3520,
    grandTotal: 35520,
  },
  {
    id: "#ORD-READY-2001",
    createdAt: now - 18 * 60 * 1000,
    source: "WALK_IN",
    status: "PAID",
    fulfillment: "READY",
    customerName: "Meja 7",
    tableLabel: "Meja 7",
    serviceMode: "DINE_IN",
    items: [
      {
        id: "ready-item-1",
        productId: "mie-ayam",
        name: "Mie Ayam",
        qty: 2,
        unitPrice: 18000,
      },
    ],
    payments: [
      {
        id: "ready-payment-1",
        method: "qris",
        amountPaid: 39960,
        paidAt: now - 16 * 60 * 1000,
      },
    ],
    subtotal: 36000,
    discountAmount: 0,
    taxAmount: 3960,
    grandTotal: 39960,
  },
  {
    id: "#ORD-KDS-2002",
    createdAt: now - 8 * 60 * 1000,
    source: "WALK_IN",
    status: "PAID",
    fulfillment: "PREPARING",
    customerName: "Takeaway - Arif",
    tableLabel: "Takeaway",
    serviceMode: "TAKEAWAY",
    items: [
      {
        id: "ready-item-2",
        productId: "ayam-geprek",
        name: "Ayam Geprek",
        qty: 1,
        unitPrice: 28000,
      },
    ],
    payments: [
      {
        id: "ready-payment-2",
        method: "tunai",
        amountPaid: 31080,
        amountReceived: 50000,
        paidAt: now - 7 * 60 * 1000,
      },
    ],
    subtotal: 28000,
    discountAmount: 0,
    taxAmount: 3080,
    grandTotal: 31080,
  },
];
